Models/WorkoutProgramme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Fitness4Life.Models
{
    
    public class WorkoutProgramme
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        [DisplayName("Title")]
        public string Title { get; set; }

        [Required]
        [StringLength(100)]
        [DisplayName("Text")]
        public string Text { get; set; }
        
        //public List<WorkoutProgramme> WorkoutProgrammes { get; set; }
    }
}

Controllers/GeneratorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fitness4Life.Data;
using Fitness4Life.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;


namespace Fitness4Life.Controllers
{
    public class GeneratorController : Controller
    {
        private readonly ILogger<GeneratorController> _logger;
        private readonly ApplicationDbContext _db;


        public GeneratorController(ILogger<GeneratorController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }
        

        [Authorize]
       
        // GET: Authors
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View("_GeneratePartial",await _db.WorkoutProgrammes.ToListAsync());
        }

        // GET: Authors/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var author = await _db.WorkoutProgrammes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View("_GeneratePartial");
        }
        
        public IActionResult Generator()
        {
            return View();
        }
        
        public ActionResult Generate(WorkoutProgramme workoutProgramme)
        {
            return PartialView("_GeneratePartial");
        }
        
        public IActionResult WorkoutProgramme()
        {
            return View();
        }
    }
}

Views/Generator/Generator.cshtml
@model Question

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Workout Generator</h1>
    </div>
</section>

<form id="GeneratorForm" asp-controller="Generator" asp-action="Generate">
    <div class="Questions">
        <div class="Question">
            <label asp-for="Choice"></label>
        </div>
        <div class="choice">
            <input type="radio" asp-for="Choice" id="Choice1_1" value="STRENGTH">
            <label asp-for="Choice">STRENGTH</label>
        </div>
        
        <div class="choice">
            <input type="radio" asp-for="Choice" class="choice" id="Choice1_2" value="CARDIO">
            <label asp-for="Choice">CARDIO</label>
        </div>
        
        <div class="choice">
            <input type="radio" asp-for="Choice" class="choice" id="Choice1_3 " value="MOBILITY">
            <label asp-for="Choice">MOBILITY</label>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label"></label>
            <div class="col-md-4">
                <button id="jquerybtn" class="btn btn-primary">Generate</button>
            </div>
        </div>
    </div>
    

</form>

<div id="content">
    <p></p>
</div>

@section Scripts
{
    <script>
    $(function()
    {
        // Hook up the click handler
        $('#jquerybtn').click(function()
        {
            $("#content").load("Generator/Generate", $('#GeneratorForm').serialize());
            
            return false;
        });
    });

</script>
}

Views/Generator/WorkoutProgramme.cshtml
<partial name="_GeneratePartial" />