Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fitness4Life.Data;
using Fitness4Life.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Fitness4Life.Controllers
{
    public class ForumController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _um;

        public ForumController(ApplicationDbContext context, UserManager<ApplicationUser> um)
        {
            _context = context;
            _um = um;
        }

        // GET: Forum/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: Forum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Message,Time")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = _um.GetUserAsync(User).Result;
                forum.ApplicationUser = user;
                
                _context.Add(forum);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Posting");
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", forum.ApplicationUserId);
            return View(forum);
        }

        // GET: Forum/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ApplicationUser user = _um.GetUserAsync(User).Result;
            var forum1 = await _context.Forums
                .Include(b => b.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
          
            if (forum1.ApplicationUserId != user.Id)
            {
              
                return RedirectToAction("Index", "Posting");
            }
            if (id == null)
            {
                return NotFound();
            }
            var forum = await _context.Forums.FindAsync(id);
            if (forum == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", forum.ApplicationUserId);
            return View(forum);
        }

        // POST: Forum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize ]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Message,Time")] Forum forum)
        {
            if (id != forum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(forum);
                    ApplicationUser user = _um.GetUserAsync(User).Result;
                    forum.ApplicationUser = user;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ForumExists(forum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Posting");
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.Users, "Id", "Id", forum.ApplicationUserId);
            return View(forum);
        }

        // GET: Forum/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ApplicationUser user = _um.GetUserAsync(User).Result;
            
            if (id == null)
            {
                return NotFound();
            }

            var forum = await _context.Forums
                .Include(b => b.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (forum == null)
            {
                return NotFound();
            }
            if (forum.ApplicationUserId != user.Id)
            {
                return NotFound();
            }

            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var forum = await _context.Forums.FindAsync(id);
            _context.Forums.Remove(forum);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Posting");
        }

        private bool ForumExists(int id)
        {
            return _context.Forums.Any(e => e.Id == id);
        }
    }
}

Controllers/PostingController.cs
using System.Linq;
using System.Threading.Tasks;
using Fitness4Life.Data;
using Fitness4Life.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Fitness4Life.Controllers
{
    public class PostingController : Controller
    {
        
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _um;

        public PostingController(ApplicationDbContext db, UserManager<ApplicationUser> um)
        {
            _db = db;
            _um = um;
        }
        // GET
        public IActionResult Index()
        {
            ForumCommentViewModel vm = new ForumCommentViewModel();
            vm.Forums = _db.Forums.OrderByDescending(a =>a.Id).Include(d =>d.ApplicationUser);
            vm.Comments = _db.Comments.OrderByDescending(a => a.CommentId).Include(d => d.ApplicationUser);
            return View(vm);
        }
        [Authorize]
        public async Task<ActionResult> CreateAdd(CommentViewModel obj)
        {
            {
                if (obj.Comment == null)
                {
                    return NotFound();
                }
                var fid = obj.FID;
                ApplicationUser user = _um.GetUserAsync(User).Result;
                var r = new Comment();
                r.Summary = obj.Comment;
                r.ForumId = obj.FID;
                r.ApplicationUserId = user.Id;
                _db.Add(r);
                await _db.SaveChangesAsync();
                return RedirectPermanent($"Next/{obj.FID}");
            }
        }
        [Authorize]
        public  IActionResult Next(int? id)
        {
            
            ForumCommentViewModel vm = new ForumCommentViewModel();
            vm.Forums = _db.Forums.OrderByDescending(a =>a.Id).Include(d =>d.ApplicationUser);
            vm.Comments = _db.Comments.OrderByDescending(a =>a.CommentId).Include(d =>d.ApplicationUser);
            ViewBag.item = id;
            return View(vm);
        }
         // GET: Comment/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            ApplicationUser user = _um.GetUserAsync(User).Result;
            var comment1 = await _db.Comments
                .Include(b => b.ApplicationUser)
                .Include(b =>b.Forum)
                .FirstOrDefaultAsync(m => m.CommentId == id);
          
            if (comment1.ApplicationUserId != user.Id)
            {

                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            var comment = await _db.Comments.FindAsync(id);
            if (comment == null)
            {
                return NotFound();
            }
            ViewData["ApplicationUserId"] = new SelectList(_db.Users, "Id", "Id", comment.ApplicationUserId);
            return View(comment1);
        }

        // POST: Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize ]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CommentId,Summary, ForumId ,Time")] Comment comment)
        {
            if (id != comment.CommentId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(comment);
                    ApplicationUser user = _um.GetUserAsync(User).Result;
                    comment.ApplicationUser = user;
                    comment.ApplicationUserId = user.Id;
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CommentExists(comment.CommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction("Next", "Posting", new {id = comment.ForumId});
            }
            ViewData["ApplicationUserId"] = new SelectList(_db.Users, "Id", "Id", comment.ApplicationUserId);
            return RedirectToAction("Next", "Posting", new {id = comment.ForumId});
        }

        // GET: Comment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ApplicationUser user = _um.GetUserAsync(User).Result;
            
            if (id == null)
            {
                return NotFound();
            } 
            
            var comment = await _db.Comments
                .Include(b => b.ApplicationUser)
                .FirstOrDefaultAsync(m => m.CommentId == id);
            if (comment == null)
            {
                return NotFound();
            }

            if (comment.ApplicationUserId != user.Id)
            {
                return NotFound();
            }

            return View(comment);
        }

        // POST: Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _db.Comments.FindAsync(id);
            _db.Comments.Remove(comment);
            _db.Comments.Include(b => b.Forum);
            await _db.SaveChangesAsync();
            return RedirectToAction("Next", "Posting", new {id = comment.ForumId});
        }
        private bool CommentExists(int id)
        {
            return _db.Comments.Any(e => e.CommentId == id);
        }
    }
}

Views/Posting/Delete.cshtml
@model Fitness4Life.Models.Comment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
    </dl>
    
    <form asp-controller="Posting" asp-action="Delete">
        <input type="hidden" asp-for="CommentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
    </form>
</div>

Views/Posting/Edit.cshtml
@model Fitness4Life.Models.Comment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Posting" asp-action="Edit" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CommentId" />
              <input type="hidden" asp-for="ForumId" />
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save"  class="btn btn-primary" asp-route="@Model.CommentId" />
            </div>
        </form>
    </div>
</div>

<div>
</div>

Views/Posting/Index.cshtml
@model ForumCommentViewModel
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.WebUtilities
@using Microsoft.CodeAnalysis.CSharp.Syntax
@using Microsoft.EntityFrameworkCore
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Index";
    Layout = "_Layout";
}
<body id="bodyy">
@if (SignInManager.IsSignedIn(User))
{
    <div class="inner-sidebar-header justify-content-center">

        <a asp-controller="Forum" asp-action="Create" class="btn btn-primary has-icon btn-block">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus mr-2">
                <line x1="12" y1="5" x2="12" y2="19"></line>
                <line x1="5" y1="12" x2="19" y2="12"></line>
            </svg>
        </a>
    </div>
}
@foreach (var item in Model.Forums)
    {
        <div class="container">
            <div class="col-lg-12">
                    <div class="wrapper wrapper-content animated fadeInRight">
                        <div class="ibox-content forum-container">
                                <div id="forum-item" class="forum-item active">
                                    <div class="row">
                                        <div class="col-md-7">
                                            <div class="forum-icon">
                                                <i class="fa fa-shield"></i>
                                            </div>
                                            <a class="forum-item-title" asp-controller="Posting" asp-action="Next" asp-route-id="@item.Id">@item.Title
                                            </a>
                                            <div class="forum-sub-title">@item.ApplicationUser.Nickname</div>
                                        </div>
                                        <div>
                                            <div class="col-md-2 forum-info">
                                                <span id="FTime">
                                                   @foreach (var comm in Model.Comments)
                                                   {
                                                       @if (item.Id == comm.ForumId)
                                                       {
                                                           @item.Comments.Count
                                                       }
                                                   }
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-3 forum-info">
                                            <span id="FTime">
                                               @item.Time 
                                            </span>
                                            <div>
                                                <small>
                                                    @if (SignInManager.IsSignedIn(User))
                                                    {
                                                        @if (item.ApplicationUserId == UserManager.GetUserId(User))
                                                            {
                                                                <a asp-controller="Forum" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                                                <a asp-controller="Forum" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                                            }
                                                    }
                                                </small>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
            </div>
        </div>
    }
</body>

Views/Posting/Next.cshtml
@model ForumCommentViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<body id="bodyy">
@{
    var Fm = (int) ViewData["item"];
    @foreach (var item in Model.Forums)
    {
    @if (item.Id == Fm)
    {
<div class="container">
<div class="col-lg-12">
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="ibox-content forum-container">
            <div id="forum-item" class="forum-item active">
                <div class="row">
                    <div class="col-md-7">
                        <div class="forum-icon">
                            <i class="fa fa-shield"></i>
                        </div>
                        <a class="forum-item-title">@item.Title
                        </a>
                        <div class="forum-sub-title">@item.Message</div>
                    </div>
                    <div class="col-md-3 forum-info">
                        <span id="FTime" class="views-number">
                            @item.Time
                        </span>
                        <div class="forum-sub-title">@item.ApplicationUser.Nickname</div>
                    </div>        
                    @if (SignInManager.IsSignedIn(User))        
                    {
                        @foreach (var comm in Model.Comments)
                        {
                            if (item.Id == comm.ForumId)
                            {
                                <div class="container">
                                    <div class="col-lg-12">
                                        <div class="wrapper wrapper-content animated fadeInRight">
                                            <div class="ibox-content forum-container">
                                                <div id="forum-item" class="forum-item active">
                                                    <div class="row" id="nick">
                                                        <div class="col-md-7">
                                                            <a class="forum-item-title">@comm.ApplicationUser.Nickname</a>
                                                        </div>       
                                                        <div class="col-md-2 forum-info">
                                                            <span id="FTime">@item.Time</span>
                                                        </div>    
                                                        <div>
                                                            <small>
                                                                @if (SignInManager.IsSignedIn(User))
                                                                {
                                                                    @if (comm.ApplicationUserId == UserManager.GetUserId(User))
                                                                    {
                                                                        <a asp-controller="Posting" asp-action="Delete" asp-route-id="@comm.CommentId">Delete</a>
                                                                        <a asp-controller="Posting" asp-action="Edit" asp-route-id="@comm.CommentId">Edit</a>
                                                                            
                                                                    }
                                                                }
                                                            </small>    
                                                        </div>    
                                                    </div>
                                                    <div class="row" id="nick">
                                                        <div id="box-message">@comm.Summary</div> 
                                                    </div>
                                                </div>    
                                            </div>
                                        </div>
                                    </div>  
                                </div>    
                                                        
                            }
                        }
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        @using (Html.BeginForm("CreateAdd", "Posting", FormMethod.Post))
                        {
                            <div class="content">
                                <input id="create-m-box" class="comment-box" type="text" name="Comment"/>
                            </div>   
                            <input type="hidden" name="FId" value="@item.Id"/>
                            <br/>
                            <div class="content">
                                <input type="submit" value="Comment" class="btn btn-success"> 
                            </div>  
                        }
                    }
                                    
                </div>
            </div>
        </div>
    </div>
</div>
</div> 
}
}    
}
</body>