Areas/Workout/Controllers/MuscleGroupsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Fitness4Life.Areas.Workout.Controllers
{
    [Area("Workout")]
    public class MuscleGroupsController : Controller
    {
        // Index / Frontpage of sub-page "Muscle Groups"
        public IActionResult Index()
        {
            return View();
        }
        
        // Traps sub-page
        public IActionResult Lats()
        {
            return View();
        }
        
        // Back sub-page
        public IActionResult Back()
        {
            return View();
        }
        
        // Shoulders sub-page
        public IActionResult Shoulders()
        {
            return View();
        }
        
        // Chest sub-page
        public IActionResult Chest()
        {
            return View();
        }
         
        // Biceps sub-page
        public IActionResult Biceps()
        {
            return View();
        }
         
        // Triceps sub-page
        public IActionResult Triceps()
        {
            return View();
        }
         
        // Forearms sub-page
        public IActionResult Forearms()
        {
            return View();
        }
         
        // Abs sub-page
        public IActionResult Abs()
        {
            return View();
        }
         
        // Glutes sub-page
        public IActionResult Glutes()
        {
            return View();
        }
         
        // Hamstrings sub-page
        public IActionResult Hamstrings()
        {
            return View();
        }
         
        // Calves sub-page
        public IActionResult Calves()
        {
            return View();
        }
         
        // Quads sub-page
        public IActionResult Quads()
        {
            return View();
        }
    }
}

Areas/Workout/Controllers/WorkoutController.cs
using Microsoft.AspNetCore.Mvc;


namespace Fitness4Life.Areas.Workout.Controllers
{
    [Area("Workout")]
    public class WorkoutController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
        
        // HomeWorkouts
        public IActionResult HomeWorkouts()
        {
            return View();
        }
        
        // GymWorkouts
        public IActionResult GymWorkouts()
        {
            return View();
        }
    }
}

Areas/Workout/Views/Workout/GymWorkouts.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Gym Workout</h2>

Areas/Workout/Views/Workout/HomeWorkouts.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Home Workout</h2>

Areas/Workout/Views/Workout/Index.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<center><h1>Workout</h1></center>

<br>
<br>

<center><h2>Workout by Gender</h2></center>


<table style="width:100%">
    <tr>
        <th>
            <center>@Html.ActionLink("Male","Index","MuscleGroups",new{area="Workout"},null)</center>
        </th>
        <th>
            <center>@Html.ActionLink("Female","Index","MuscleGroups",new{area="Workout"},null)</center>
        </th>
    </tr>
</table>